# Generated by Django 4.2.14 on 2024-08-03 17:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(auto_created=True, default='[]', editable=False, verbose_name='Comments')),
                ('price', models.BigIntegerField(auto_created=True, blank=True, null=True, verbose_name='Price sold')),
                ('quantity', models.IntegerField(auto_created=True, default=0, verbose_name='Sold quantity')),
                ('status', models.CharField(auto_created=True, choices=[('New', 'New'), ('Refused', 'Refused'), ('Approved', 'Approved'), ('Need approved', 'Need approved')], default='New', max_length=50, verbose_name='Lead status')),
                ('name', models.CharField(default='Anonym', max_length=200, verbose_name='Customer name')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='Phone number')),
                ('request_date', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Request date')),
                ('address', models.CharField(choices=[('Tashkent', 'Tashkent'), ('Andijan', 'Andijan'), ('Bukhara', 'Bukhara'), ('Jizzakh', 'Jizzakh'), ('Kashkadarya', 'Kashkadarya'), ('Navoi', 'Navoi'), ('Namangan', 'Namangan'), ('Samarkand', 'Samarkand'), ('Surkhandarya', 'Surkhandarya'), ('Syrdarya', 'Syrdarya'), ('Tashkent region', 'Tashkent region'), ('Fergana', 'Fergana'), ('Khorezm', 'Khorezm'), ('Republic of Karakalpakstan', 'Republic of Karakalpakstan')], max_length=30, verbose_name='Address')),
                ('product', models.CharField(choices=[('Lactos', 'Lactos'), ('Laditex', 'Laditex'), ('PerfectMan', 'PerfectMan')], max_length=50, verbose_name='Product')),
                ('operator', models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='AccountDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datas', models.TextField(auto_created=True, default='{}', verbose_name='Extra datas')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6, verbose_name='Gender')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='Phone number')),
                ('last_online', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last online')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Account data',
                'verbose_name_plural': 'Account datas',
            },
        ),
    ]
