# Generated by Django 4.2.14 on 2024-08-07 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_accountdatas_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='sold_date',
            field=models.CharField(default='10/10/2024', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Sold date'),
        ),
    ]
