# Generated by Django 5.1 on 2024-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_leads_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatas',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Operator', 'Operator'), ('Rob', 'Rob')], default='Operator', max_length=8, verbose_name='Role'),
        ),
    ]
