# Generated by Django 5.1 on 2024-08-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_accountdatas_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='regwarded',
            field=models.BooleanField(default=False, verbose_name='Regwarded'),
        ),
    ]
