# Generated by Django 5.1 on 2024-08-21 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_accountdatas_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='call_count',
            field=models.IntegerField(default=0, verbose_name='Call count'),
        ),
        migrations.AddField(
            model_name='leads',
            name='lead_calldate',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Call date'),
        ),
    ]
