# Generated by Django 5.1 on 2024-08-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_leads_call_count_leads_lead_calldate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Content')),
                ('pinned_file', models.FileField(upload_to='comments/', verbose_name='Pinned file')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.accountdatas', verbose_name='Comment owner')),
            ],
            options={
                'verbose_name': 'Lead comment',
                'verbose_name_plural': 'Leads comments',
            },
        ),
    ]
