# Generated by Django 5.1 on 2024-08-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_lead_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_comments',
            name='lead',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.leads', verbose_name='Refer to lead'),
        ),
    ]
