# Generated by Django 5.1 on 2024-08-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_lead_comments_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_comments',
            name='pinned_file',
            field=models.FileField(blank=True, null=True, upload_to='comments/', verbose_name='Pinned file'),
        ),
    ]
