# Generated by Django 5.1 on 2024-08-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_lead_comments_pinned_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='product',
            field=models.CharField(choices=[('Lactos', 'Lactos'), ('Laditex', 'Laditex'), ('PerfectMan', 'PerfectMan'), ('Tribgen', 'Tribgen')], max_length=50, verbose_name='Product'),
        ),
    ]
