# Generated by Django 5.1 on 2024-08-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_leads_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Customer name'),
        ),
    ]
